language: node_js
node_js:
  - 8.4.0
before_install:
  - openssl aes-256-cbc -K $encrypted_ca388522c6bc_key -iv $encrypted_ca388522c6bc_iv -in deploy_key.enc -out /tmp/deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_key
  - ssh-add /tmp/deploy_key
script: yarn test
before_deploy:
- chmod +x deploy.sh
deploy:
  provider: script
  script: "./deploy.sh"
  on: master
addons:
  ssh_known_hosts: leaderboard.chester.how
