version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://db:27017/leaderboard
      - ROOT_URL=http://localhost:3000
      - PORT=3000
    command: node /app/bundle/main.js
    depends_on:
      - db
  db:
    image: mongo:3.5
    ports:
      - 27017:27017
